Feature/ode 43
ode-to-coders/multiplayer-game pull request #29
Opened 2023-05-10 11:26 UTC by shinonhorror

### Какую задачу решаем
Настроить Express для Server Side Rendering (без Redux, просто отдавать React-страничку)

Как запускать:
1. `yarn bootstrap`
2. `yarn build`
3. `yarn preview —scope client`
4. `yarn preview —scope server`

2023-05-10 11:28 UTC, aleksakko approved these changes

2023-05-10 11:41 UTC, lusorich approved these changes

2023-05-10 15:01 UTC, IvanPeleshok commented on packages/client/src/app/ui/App/App.tsx
> +  const { hasMounted } = useMounted();
Суть хука понятна, но для каких целей необходимо рендерить дочерние компоненты только после того, как будет вмонтирован компонент?

2023-05-10 15:06 UTC, IvanPeleshok commented on packages/client/src/app/ui/App/App.tsx
>    if (isAuth) {
Необходимо соблюдать соглашение, что функциональный компонент имеет конечный return с JSX
Предлагаю переписать на следующий вид:

return isAuth
  ? JSX
  : JSX

2023-05-10 15:09 UTC, IvanPeleshok commented on packages/client/src/app/ui/AuthenticatedApp/AuthenticatedApp.tsx
> +      const url = `http://localhost:${__SERVER_PORT__}/api`;
Было бы здорово заменить такие вещи на переменные окружения и вынести всё в .env

2023-05-10 15:10 UTC, IvanPeleshok requested changes
Есть замечания

2023-05-10 15:54 UTC, shinonhorror commented on packages/client/src/app/ui/App/App.tsx
>    const { isFetching, isAuth } = useAuth();
Исправлено

2023-05-10 15:55 UTC, shinonhorror commented on packages/client/src/app/ui/App/App.tsx
> +  const { hasMounted } = useMounted();
Падала ошибка гидратации компонентов и ssr переставал работать, поэтому был такой костыль сделан. Это единственное решение, все остальное не работало от слова совсем.

2023-05-10 19:24 UTC, IvanPeleshok commented on packages/client/src/app/ui/App/App.tsx
> +  const { hasMounted } = useMounted();
@shinonhorror, обсуждала этот момент с ментором?

2023-05-10 19:26 UTC, IvanPeleshok commented on packages/client/src/app/ui/AuthenticatedApp/AuthenticatedApp.tsx
> +      const url = __CLIENT_URL__;
process.env.ENV_VARIABLE

2023-05-10 19:26 UTC, IvanPeleshok commented on packages/client/src/app/ui/UnauthenticatedApp/UnauthenticatedApp.tsx
> +      const url = __CLIENT_URL__;
process.env.ENV_VARIABLE

2023-05-11 23:06 UTC, IvanPeleshok approved these changes

2023-05-12 09:10 UTC, merged