Feature/ode44
ode-to-coders/multiplayer-game pull request #30
Opened 2023-05-12 14:18 UTC by Lihappinesss

### Какую задачу решаем
Добавила store и роутинг для рендера на севрере

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-14 18:31 UTC, shinonhorror approved these changes

2023-05-14 18:31 UTC, shinonhorror commented on packages/client/ssr.tsx
>        <Provider store={store}>
Лучше прокидывать стор, который был на сервере создан сюда, т.е. функция render будет принимать три аргумента: url, cache, store. 
`render(url: string, cache: any, store: storeProps) {
  return renderToString(
    <CacheProvider value={cache}>
      <Provider store={store}>`

2023-05-14 18:54 UTC, lusorich approved these changes

2023-05-17 19:17 UTC, Lihappinesss commented on packages/client/ssr.tsx
>        <Provider store={store}>
Поправила. А почему так лучше?

2023-05-18 10:08 UTC, IvanPeleshok commented on package.json
> +    "@types/react-alert": "7.0.2",
Подумай, возможно есть смысл что-то вынести в дев зависимости

2023-05-18 11:50 UTC, IvanPeleshok commented on packages/client/src/app/store/store.ts
> +      };
Форматирование некорректное
```
условие
? {}
? {
    ...
}
```

2023-05-18 11:51 UTC, IvanPeleshok commented on packages/client/src/app/store/store.ts
> +      auth: authSlice.getInitialState(),
Не хватает отступа

2023-05-18 11:53 UTC, IvanPeleshok requested changes
Есть замечания

2023-05-20 10:04 UTC, Lihappinesss commented on package.json
> +    "@types/react-alert": "7.0.2",
Перенесла

2023-05-20 10:04 UTC, Lihappinesss commented on packages/client/src/app/store/store.ts
> +      auth: authSlice.getInitialState(),
Добавила

2023-05-21 21:46 UTC, IvanPeleshok approved these changes

2023-05-22 20:03 UTC, merged